<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">

<html lang="en-GB">

<head>
  <title>Micron Oxford Advanced Bioimaging: mDSLM</title>
  <meta http-equiv="Content-Type" CONTENT="text/html; charset=UTF-8">
  <link rel="stylesheet" type="text/css" href="../styles/micron_main.css" >
  <link rel="stylesheet" type="text/css" href="../styles/micron_facilities.css" >
  <link rel="icon" type="image/ico" href="../images/MicronMu.ico" >
  <script src="../google_analytics.js"></script>
</head>

<body id="facilities">
  <div id="container_all">
    <?php include "../headnav.html"; ?>
    <div id="mainbody">
      <div id="leftpanel">

        <h3>mDSLM Light Sheet Microscope</h3>
        <p>New Biochmistry Room 00-060</p>
        <p>&nbsp;</p>
<p>This is a cutting-edge fluorescence microscope designed primarily for time-lapse imaging of thick specimens that a scanning confocal microscope would struggle with. Imaging of thick, fixed samples is also possible. Specimens are illuminated with a thin light sheet generated by a fast-scanned, focussed laser beam perpendicular to the detection objective. This vastly reduces light exposure and therefore bleaching of the sample and enables penetration depths of up to 100 um. It is possible to image in single or multiview mode, the latter through rotating the sample and imaging stacks at six to eight different angles, which can then be recombined into a 360° view. Specimens are embedded in 1% low-melting agarose inside glass capillaries and then extruded and imaged in buffer.</p>
<p>&nbsp;</p>

            <table width="100%"  border="1" align="left" cellpadding="4">
  <tr>
    <th width="13%" scope="col"><span class="style1"><strong>Laser</strong></span></th>
    <th width="23%" scope="col"><span class="style1"><strong>Excitation Lines </strong></span></th>
    <th width="64%" scope="col"><span class="style1"><strong>Suitable Dyes </strong></span></th>

  </tr>
  <tr>

    <td rowspan="3"><span class="style1">diode laser</span></td>
    <td bgcolor="#33FF66"><span class="style13">488nm</span></td>
    <td>Alexa 488, FITC, GFP, Cy2</td>
  </tr>
  <tr>

  </tr>
  <tr>
  </tr>
  <tr>
    <td><span class="style1">DPSS solid state</span></td>

    <td bgcolor="#FF9900"><span class="style1">561nm</span></td>
    <td><span class="style1">Alexa 546, TRITC, Cy3, DiI, propidium iodide, Texas red , mCherry </span></td>
  </tr>
  <tr>
    <td><span class="style1">diode laser</span></td>
    <td bgcolor="#FF0000"><span class="style13">638nm</span></td>
    <td><span class="style1">Alexa 633, Alexa 647, Cy5</span></td>

  </tr>
</table>


<p>&nbsp;</p>

            <table width="100%"  border="1" align="left" cellpadding="4">
  <tr>
    <th width="48%" class="style14" scope="col">Objectives</th>
    
    <th width="52%" class="style14" scope="col"></th>
    </tr>
  <tr>
    <td><p class="style1">10x/0.30 water immersion<br />
      20x/0.5 water immersion<br />
      40x/0.75 water immersion<br />
      </p>
      </td>
    <td><span class="style1"><br />
      <br />
       </span></td>
    </tr>
</table>
 
      </div>

      <div id="rightpanel">
        <a name="software">
        <img id="OMX V2" src="images/mDSLM_thumb.jpg"  width="200" height="133"
              alt="mDSLM" title="mDSLM Light Sheet Microscope"/>
        <p></p>
        <ul>
          <li><a href="../resources/mDSLM User Manual 01.pdf" target="_blank">DSLM user Manual</a></li>
          <li><a href="http://micronwiki.bioch.ox.ac.uk/wiki/mDLSM" target="_blank">mDSLM Wiki</a></li>
        </ul>
      </div>

    </div>
    <?php include "../footer.html"; ?>
  </div>
</body>

</html>

