<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">

<html lang="en-GB">

<head>
  <title>Micron Oxford Advanced Bioimaging: mDSLM</title>
  <meta http-equiv="Content-Type" CONTENT="text/html; charset=UTF-8">
  <link rel="stylesheet" type="text/css" href="../styles/main.css" >
  <link rel="stylesheet" type="text/css" href="../styles/facilities.css" >
  <link rel="icon" type="image/ico" href="../images/MicronMu.ico" >
  <script src="../google_analytics.js"></script>
</head>

<body id="facilities">
  <div id="container_all">
    <?php include "../headnav.html"; ?>
    <div id="mainbody">
      <div id="leftpanel">

        <?php
          include "../scripts/microscopes.php";
          use MicronOxford\OpticalMicroscope;
          use MicronOxford\Laser;
          use MicronOxford\Objective;

          $mDSLM = new OpticalMicroscope (
            "mDSLM",
            "mDSLM Light Sheet",
            "New Biochmistry Room 00-060",
            array (
              new Laser (488, "Diode laser"),
              new Laser (561, "DPSS solid state"),
              new Laser (638, "Diode laser"),
            ),
            array (
              new Objective (10, 0.30, "Water immersion"),
              new Objective (20, 0.50, "Water immersion"),
              new Objective (40, 0.75, "Water immersion"),
            )
          );
        ?>

        <?php $mDSLM->draw_header (); ?>

        <p>
          This is a cutting-edge fluorescence microscope designed primarily
          for time-lapse imaging of thick specimens that a scanning confocal
          microscope would struggle with. Imaging of thick, fixed samples is
          also possible. Specimens are illuminated with a thin light sheet
          generated by a fast-scanned, focussed laser beam perpendicular to
          the detection objective. This vastly reduces light exposure and
          therefore bleaching of the sample and enables penetration depths of
          up to 100 µm. It is possible to image in single or multiview mode,
          the latter through rotating the sample and imaging stacks at six to
          eight different angles, which can then be recombined into a 360°
          view. Specimens are embedded in 1% low-melting agarose inside
          glass capillaries and then extruded and imaged in buffer.
        </p>

        <?php $mDSLM->draw_description (); ?>

      </div>

      <div id="rightpanel">
        <img src="../images/mDSLM_thumb.jpg" width="200"/>
        <ul>
          <li><a href="../resources/mDSLM User Manual 01.pdf" >DSLM user Manual</a></li>
          <li><a href="http://micronwiki.bioch.ox.ac.uk/wiki/mDLSM" >mDSLM Wiki</a></li>
        </ul>
      </div>

    </div>
    <?php include "../footer.html"; ?>
  </div>
</body>

</html>

